name: Handyman.AspNetCore

on:
  push:
    paths:
    - 'src/Handyman.AspNetCore/src/**'
    - 'src/Handyman.AspNetCore/tests/**'
  pull_request:
    paths:
    - 'src/Handyman.AspNetCore/src/**'
    - 'src/Handyman.AspNetCore/tests/**'
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to nuget (true/false)'
        required: false
        default: 'false'

defaults:
  run:
    working-directory: src/Handyman.AspNetCore

jobs:
  build-test-publish:
    uses: JonasSamuelsson/Handyman/.github/workflows/build-test-publish-v1.yml
    with:
      mainProjectPath: src/Handyman.AspNetCore/src/Handyman.AspNetCore.csproj
      testProjectPath: src/Handyman.AspNetCore/tests/Handyman.AspNetCore.Tests.csproj
      publish: ${{ github.event.inputs.publish }}
    secrets:
      nuget: ${{ secrets.NUGET }}