name: Handyman.Mediator.DependencyInjection

on:
  push:
    paths:
    - '.github/workflows/Handyman.Mediator.DependencyInjection.yaml'
    - 'src/Handyman.Mediator.DependencyInjection/src/**'
    - 'src/Handyman.Mediator.DependencyInjection/tests/**'
    tags-ignore:
    - '**'
  pull_request:
    paths:
    - '.github/workflows/Handyman.Mediator.DependencyInjection.yaml'
    - 'src/Handyman.Mediator.DependencyInjection/src/**'
    - 'src/Handyman.Mediator.DependencyInjection/tests/**'
    tags-ignore:
    - '**'
  workflow_dispatch:
    inputs:
      publish_package:
        description: 'Publish to nuget (true/false)'
        required: false
        default: 'false'

defaults:
  run:
    working-directory: src/Handyman.Mediator.DependencyInjection

jobs:
  build-test-publish:
    runs-on: windows-2019
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - uses: actions/checkout@v2
    - name: setup .net core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: build
      run: dotnet build src/Handyman.Mediator.DependencyInjection.csproj --configuration release
    - name: test
      run: dotnet test tests/Handyman.Mediator.DependencyInjection.Tests.csproj --configuration release --no-restore --no-build
    - name: publish to nuget
      if: ${{ github.event.inputs.publish_package == 'true' }}
      run: |
        dotnet pack src/Handyman.Mediator.DependencyInjection.csproj --configuration release --include-symbols --no-restore --no-build --output .artifacts
        get-childitem ./.artifacts/*.nupkg | foreach-object { dotnet nuget push $_ --api-key ${{ secrets.NUGET }} --source https://api.nuget.org/v3/index.json }
