name: Handyman.DependencyInjection

on:
  push:
    paths:
      - src/Handyman.DependencyInjection/src/**
      - src/Handyman.DependencyInjection/tests/**
  pull_request:
    paths:
      - src/Handyman.DependencyInjection/src/**
      - src/Handyman.DependencyInjection/tests/**
  workflow_dispatch:
    inputs:
      publish:
        description: Publish to nuget
        required: false
        type: boolean
        default: false

jobs:
  build-test-publish:
    uses: JonasSamuelsson/Handyman/.github/workflows/build-test-publish-v1.yml@master
    with:
      mainProjectPath: src/Handyman.DependencyInjection/src/Handyman.DependencyInjection.csproj
      testProjectPath: src/Handyman.DependencyInjection/tests/Handyman.DependencyInjection.Tests.csproj
      publish: ${{ github.event.inputs.publish }}
      runsOn: windows-2022
    secrets:
      nuget: ${{ secrets.NUGET }}
